seperate aci

diff --git a/.github/workflows/Create 3 resource.yml b/.github/workflows/Create 3 resource.yml
--- a/.github/workflows/Create 3 resource.yml
+++ b/.github/workflows/Create 3 resource.yml
@@ -129,3 +129,19 @@ jobs:
           && terraform apply -auto-approve -var-file="envs/${{ env.ENV }}/${{ env.ENV }}.tfvars" ./downloaded-artifacts/terraform-plan-acr/tfplan_acr \
           && terraform apply -auto-approve -var-file="envs/${{ env.ENV }}/${{ env.ENV }}.tfvars" ./downloaded-artifacts/terraform-plan-acr-secrets/tfplan_acr_secrets \
           && terraform apply -auto-approve -var-file="envs/${{ env.ENV }}/${{ env.ENV }}.tfvars" ./downloaded-artifacts/terraform-plan-key-vault/tfplan_key_vault
+
+
+      - name: Terraform Refresh State
+        run: terraform refresh
+
+      - name: Terraform Plan for ACI
+        env:
+          ARM_USE_OIDC: true
+          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+        run: |
+          terraform plan -var-file="envs/${{ env.ENV }}/${{ env.ENV }}.tfvars" \
+            -var="image_tag=${{ github.sha }}" \
+            -target=module.aci \
+            -out=tfplan_aci 2>&1 | tee terraform_aci.log || echo "Terraform Plan failed, but continuing..."
